sudo: false
language: python

install:
  - pip install tox codecov

script:
  - tox

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=py36-flake8

after_success:
  - tox -e coverage
  - codecov
