---
version: '3'

volumes:
  es_data:

networks:
  es_net:

services:
  accesspoc:
    build: .
    environment:
      - ES_HOSTS=elasticsearch:9200
    volumes:
      - ./accesspoc:/src
    ports:
      - '43430:8000'
    networks:
      - es_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '43431:9200'
    networks:
      - es_net
